# src/rag_assistant/config/models.yaml

openai:
  gpt4omini: "gpt-4o-mini"
  gpt_nano: "gpt-4.1-nano"

local:
  deepseek: "deepseek-r1:1.5b"
  llama1b: "llama3.2:1b"
  llama3b: "llama3.2:3b"
  gemma: "gemma3:4b"
